name: Test

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:

    runs-on: centos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          /bin/bash initialization.sh
